puppetlabs/puppet_metrics_dashboard

- manifests/install.pp
- spec/classes/init_spec.rb
- spec/classes/install_spec.rb
Prior to this commit we had a workaround to create a directory for the
PID file of grafana. This commit removes the workaround and adds a
method for creating the var run directory at boot. This is to address issue #12 where the service cannot start on RHEL 7 after a reboot.
> (GH12) Update systemd tmpfiles

- .fixtures.yml
- .sync.yml
- .travis.yml
- metadata.json
- spec/classes/install_spec.rb
Prior to this commit the gems were not correctly being installed and
there was a rubocop error. This commit updates the PDK to 1.6.1 to
rectify the issue and install the gems correctly.
> (maint) Update to PDK 1.6.1

- .fixtures.yml
- .sync.yml
- .travis.yml
- Gemfile
- metadata.json
- spec/spec_helper_acceptance.rb
Prior to this commit, the repo was on PDK 1.6.1 and there was no top
limit to the beaker gem. Since Beaker 4 was a breaking change, it needed
to be configured to enable the spec tests moving forward. Otherwise, we
would have encountered random failures in the CI unrelated to the changes
in PRs. This commit updates the repo to use Beaker 4.
> (maint) Update to PDK 1.7.0 and Beaker 4

- spec/classes/install_spec.rb
- templates/influxdb.conf.epp
The unless broke if an empty array was passed in. The modifications are per recommendations from @danielparks
> Removed unless block from template

- .fixtures.yml
- README.md
- REFERENCE.md
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- manifests/repos.pp
- manifests/telegraf.pp
- metadata.json
- spec/classes/telegraf_spec.rb
- spec/spec_helper_acceptance.rb
- templates/telegraf.conf.epp
Parameters added:
- influxdb_urls
- telegraf_db_name
- telegraf_agent_interval
- http_response_timeout
Global telegraf settings are now managed via ini_setting resources.
Settings for this module are moved from telegraf.conf to
telegraf.d/puppet_metrics_dashboard.conf. These changes allow configs other
than the ones for this module to be set while still allowing this module
to udpate its config.
Update .fixtures and metadata (fixes #18)
Also removed top scope references and replaced legacy facts
> Add params, separate configs

- manifests/repos.pp
- spec/classes/repos_spec.rb
Updates repo url and key, as per:
https://grafana.com/blog/2019/01/05/moving-to-packages.grafana.com/
https://github.com/voxpupuli/puppet-grafana/pull/150
> (MODULES-8585) update grafana repos

- templates/telegraf.conf.epp
This commit will add a metric showing the last time code was successfully committed to any branch.  We can use this to identify issues where any of the masters aren't getting updated code.
> add a metric for last successful file-sync commit

- manifests/service.pp
- spec/classes/service_spec.rb
This commit updates the service management logic for grafana to drop the
creation of the /run/grafana directory prior to starting the service on
CentOS 7. Grafana 4.5.0 and later manage this by setting the RuntimeDirectory
in the grafana-server.service unit file. However, CentOS 7 uses systemd v219
which will fail during startup if the directory specified by RuntimeDirectory
already exists. This failure causes the first catalog application that installs
and starts grafana-server to fail --- which is particularly problematic for
Bolt plans that only run once.
> Stop creating /run/grafana on CentOS 7

- metadata.json
The grafana module is at 6.0.0 now, so need to bump up the requirement in metadata
> fix grafana version req.

- files/Telegraf_FOSS_Puppetserver_Performance.json
- manifests/dashboards/telegraf.pp
This addresses #47.  Before this commit, the Telegraf Puppetserver Performance dashboard had `pe-` prefixed metrics, and didn't work with FOSS puppet.
This commit adds a conditional to the `puppet_metrics_dashboard::dashboards::telegraf` class that points to a new dashboard without the prefixes.  This is dependent on the presence of a `pe_server_version` fact that will not be in a FOSS install.
> Improve support for FOSS puppet dashboards

- README.md
- manifests/init.pp
- manifests/telegraf/config.pp
- spec/classes/telegraf/config_spec.rb
- spec/type_aliases/puppet_metrics_dashboard_host_list_spec.rb
- templates/telegraf.conf.epp
- types/hostlist.pp
This commit updates the master_list, puppetdb_list, and postgres_host_list
parameters to allow pairs of `[hostname, port_number]` in addition to just
a hostname. If the port number is specified, then Telegraf will be configured
to use that port when requesting metrics from the host. If no port number is
specified, then Telegraf will be configured to use the default prts of
8140 for Puppet Server, 8081 for PuppetDB, and 5432 for Postgres.
Closes puppetlabs/puppet_metrics_dashboard#48
> Allow port numbers of services to be specified

- files/Archive_File_Sync.json
- files/Graphite_Puppetserver_Performance.json
- files/PuppetDB_Performance.json
- files/PuppetDB_Workload.json
- files/Puppetserver_Performance.json
- files/Telegraf_FOSS_Puppetserver_Performance.json
- files/Telegraf_File_Sync.json
- files/Telegraf_Postgres.json
- files/Telegraf_PuppetDB_Performance.json
- files/Telegraf_PuppetDB_Workload.json
- files/Telegraf_Puppetserver_Performance.json
This PR improves the dashboard templates in two ways:
- All dashboards now use a shared crosshair. This allows values to be easily compared at the same moment in time between graphs that are not vertically stacked.
- The Archive dashboards now have a `$datasource` variable that can be used to flip between different datasources. This is allows metrics from separate PE installations to be loaded into separate InfluxDB databases without requiring dashboards to be copied for each.
Unused entries in the JSON are also cleaned up.
> Update dashboard templates

- spec/classes/telegraf/config_spec.rb
- templates/telegraf.conf.epp
Prior to this commit, the http_response_timeout did not apply to the
puppetserver status API call in telegraf, so setting it had no effect on
the timeout. This commit adds the timeout to all `inputs.http` and
`inputs.httpjson` items in the `telegraf.conf.epp`.
Prior to this PR, we were seeing timeouts on the puppetserver status endpoint and there was no way to set it in the configuration file.
> Ensure http timeout is set in all inputs.http* for telegraf

- manifests/certs.pp
- templates/telegraf.conf.epp
Previously, this module did not work for environments where certname != FQDN. With this change, certname is consistently used instead of FQDN when naming certificate/key files.
> Use certname consistently for key files

- manifests/telegraf/config.pp
Two of the PuppetDB metrics queried for, global.generate-retry-message-time
and global.retry-persistence-time, stopped being available with
PuppetDB 4.3.0. This patch uses the PE version detection logic to
correctly select the metric set to pull.
> Select PuppetDB metrics based on version

- files/Puppetserver_Performance.json
This commit updates the "Archive Puppetserver Performance" dashboard
template with two fixes for the catalog compile time metric:
- The `mean()` function is replaced with `distinct()` so that null
values are properly handled.
- The `catalog-metrics` measurement is an array of different
timings of operations that make up compilation. The query
is updated to select only `compile` and `static_compile`
operations.
> Fix archive dashboard query for compile time

- files/PuppetDB_Performance.json
- files/PuppetDB_Workload.json
- files/Telegraf_PuppetDB_Performance.json
- files/Telegraf_PuppetDB_Workload.json
This commit updates the archive and telegraf dashboards for PuppetDB:
- Several instances of rate metrics being presented as durations have
been fixed. If 8 command processing threads concurrently finish jobs
that each took 5 minutes, then the rate at that moment is 0.02 per second,
but the duration was 5 minutes.
- Graph titles and axis labels have been improved.
- Y-Axis have been changed from "short" to appropriate measurements
like "milliseconds" or "writes per second".
> Improve PuppetDB metric dashboards

- README.md
- REFERENCE.md
- data/common.yaml
- data/os/Debian.yaml
- data/os/RedHat.yaml
- functions/puppetdb_metrics.pp
- hiera.yaml
- manifests/init.pp
- manifests/profile/compiler.pp
- manifests/profile/master/postgres.pp
- manifests/profile/master/postgres_access.pp
- manifests/profile/puppetdb.pp
- spec/classes/init_spec.rb
This PR does the following:
- Switched from Hiera backend to standard function
- Created a function for determining the needed PuppetDB metrics based
on PE version
- Removed the variable 'storage_metrics_db_queries' since it was not
referenced anywhere.
- Updated the README and documentation in some manifests
This all stemmed from trying to solve the problem of having to define
the same values for parameter defaults in multiple places. The part of
this PR that addresses that exact problem is the new
`puppet_metrics_dashboard::puppetdb_metrics()` function. The rest of this
was just a by-product of getting to that solution.
> Switching to in module hiera data & updating docs

- CHANGELOG.md
- README.md
- metadata.json
> document toml-rb gem requirement

- .gitignore
- .sync.yml
- Gemfile
- Rakefile
- metadata.json
- spec/classes/config_spec.rb
- spec/classes/dashboards/graphite_spec.rb
- spec/classes/dashboards/puppet_metrics_spec.rb
- spec/classes/dashboards/telegraf_spec.rb
- spec/classes/dashboards_spec.rb
- spec/classes/grafana_spec.rb
- spec/classes/init_spec.rb
- spec/classes/install_spec.rb
- spec/classes/post_start_configs_spec.rb
- spec/classes/repos_spec.rb
- spec/classes/service_spec.rb
- spec/classes/telegraf/config_spec.rb
- spec/classes/telegraf/service_spec.rb
- spec/classes/telegraf_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_local.rb
Prior to this commit, spec tests were hanging indefinitely. This commit
fixes that issue by changing the way the facter version was specified in
the spec testing. It sets up a default facter version which is
compatible with the newer versions of `rspec-puppet-facts`. This change
also updates PDK to 1.13.0 to apply the configuration change in the
`.sync.yml`.
This resolves #74
> Fix hung spec tests

- manifests/grafana.pp
- spec/classes/grafana_spec.rb
This is based on the docs here:
https://grafana.com/docs/installation/configuration/#admin-password
And fixes #24
Note that it only sets the admin password on build, but at least it sets it
> Added ability to set default password

- .rubocop.yml
- .vscode/extensions.json
- metadata.json
- spec/default_facts.yml
Fixes #82 by updating to a newer version of the PDK and resolving issues with metadata.json that kept acceptance tests from passing.
This PR sorts the dependencies in metadata.json and makes the following actual changes:
- telegraf's upper limit is raised to < 4.0.0
- inifile's upper limit is raised to < 5.0.0
- puppetserver_gem is added
The diff post-sorting is
```diff
--- 	2020-01-02 18:36:47 +0000
+++ 	2020-01-02 18:36:47 +0000
@@ -5,7 +5,7 @@
},
{
"name": "puppet-telegraf",
-      "version_requirement": ">= 2.0.0 < 3.0.0"
+      "version_requirement": ">= 2.0.0 < 4.0.0"
},
{
"name": "puppetlabs-apt",
@@ -13,10 +13,14 @@
},
{
"name": "puppetlabs-inifile",
-      "version_requirement": ">= 2.0.0 < 4.0.0"
+      "version_requirement": ">= 2.0.0 < 5.0.0"
+    },
+    {
+      "name": …
```
> (INFC-19230) Updated to pdk 1.15.0, fix metadata.json

- README.md
- REFERENCE.md
- data/common.yaml
- functions/localhost_or_hosts_with_pe_profile.pp
- manifests/init.pp
- manifests/profile/master/install.pp
- manifests/profile/master/postgres_access.pp
With this commit ...
Simplify and sort information in README.md.
Document issue with hostnames versus domain names (dots) and Graphite.
Correct toml-rb gem requirements: only needed in Puppet Server.
Require puppetserver_gem module to install toml-rb gem.
Add profile::master::install class to install toml-rb gem.
Clarify issue with profile::master::postgres_access and pe-postgres resources.
Automate *_list parameters.
Group similar parameters in init.pp and common.yaml.
Document that class parameter defaults are defined in common.yaml.
> refactor documentation and simplify installation

- CHANGELOG.md
- files/Archive_File_Sync.json
- files/Puppetserver_Performance.json
- files/Telegraf_File_Sync.json
- spec/acceptance/install_spec.rb
Version 5.3.0 of the metrics collector removed several of these metrics,
as they were duplicates.  The dashboards in this commit should work with
any version of PE >= 2017.3.x
> Remove deprecated pe- metrics

- files/Telegraf_Puppetserver_Performance.json
Prior to this commit, we used the pe-jruby metrics in the example
dashboards. Since these were released into the open source puppet
versions in 5.3.x, we can now use the `jruby` to ensure compatiblity with
OSP and puppetlabs-puppet_metrics_collector/pull/29. This change updates
the dashboards to use `puppetserver.jruby` instead of `puppetserver.pe-jruby`.
> Use the `puppetserver.jruby` metrics in the dashboard examples

- CHANGELOG.md
- manifests/profile/compiler.pp
- manifests/profile/master/install.pp
- manifests/profile/master/postgres.pp
- manifests/profile/master/postgres_access.pp
- manifests/profile/puppetdb.pp
This PR has some basic OSP compatibility updates to the module. It includes the following. 
* Use the client certificate for all PuppetDB API requests
* ~~Update the `pe_server_version` conditionals to check if `NotUndef`~~
* Remove the file sync query from PuppetDB when `pe_server_version` is not defined
* Allow for specifying the PostgreSQL databases in the profile
* Failing on the `postgres_access` class if it is OSP since it uses PE classes and we cannot guarantee the method used in OSP.
The biggest change is the client certificates on the PuppetDB API requests over skipping validation.
This is a draft PR since there are no spec tests on these profiles and want to identify what is appropriate.
> OSP Compatibility Updates

- files/Ace_Puma_Performance.json
- files/Bolt_Puma_Performance.json
- files/Orchestration_Services.json
- files/Orchestrator_JVM_Performance.json
- files/Process_System_Stats.json
- files/PuppetDB_JVM_Performance.json
- files/PuppetDB_Workload.json
- files/Puppetserver_JVM_Performance.json
- files/Puppetserver_Performance.json
- manifests/dashboards/puppet_metrics.pp
- spec/classes/dashboards/puppet_metrics_spec.rb
added dashboards for system and process data that was recently added to Puppet metrics collector
added some new dashboards for ace and bolt data which was recently added to puppet metrics collector
Added some new dashboards for deeper dives into some of the jvms and puma services
Added a new orchestration services dashboard for ace, bolt and orch performance data.
> (SLV-788) New and updated dashboards

- CHANGELOG.md
- README.md
- files/Telegraf_PuppetDB_Performance_v2.json
- files/Telegraf_PuppetDB_Workload_v2.json
- functions/localhost_or_hosts_with_pe_profile.pp
- functions/puppetdb_no_remote_metrics.pp
- manifests/dashboards/telegraf.pp
- manifests/profile/puppetdb.pp
- manifests/telegraf/config.pp
- spec/classes/init_spec.rb
- spec/classes/telegraf/config_spec.rb
- templates/telegraf.conf.epp
This PR addresses the changes to metrics endpoints required by CVE-2020-7943:
* Returns `['localhost']` in `localhost_or_hosts_with_pe_profile()` if `puppet_version` is greater than 6.14.0 9 or greater than 5.5.19 but below v6) when the function runs on the master. If not run on the master, an empty array is returned.
* Changes the default of `puppetdb_host` in `puppet_metrics_dashboard::profile::puppetdb` to localhost. This would be overridden when called from `puppet_metrics_dashboard::telegraf::config` when a list of puppetdb hosts is returned from `localhost_or_hosts_with_pe_profile()`
* Changes metrics URLs as appropriate
* Updates dashboards with new metric value and uses the `host` tag instead of `server` (so we don't see localhost on all the dashes). 
* Adds test coverage for …
> (DIO-563) addresses CVE-2020-7943

- functions/puppetdb_metrics.pp
This changeset adds PE 2019 to the list of PuppetDB metrics so that HA sync is collected. ActiveMQ metrics are also dropped for PE 2017, 2018, and 2019 as PuppetDB switched to Stockpile in PE 2017.1.0.
> Update PE PuppetDB metrics

- spec/spec_helper_acceptance.rb
- spec/spec_helper_acceptance_local.rb
Prior to this commit, the litmus acceptance tests were failing due to an
ordering issue. This commit moves the requires into the
spec_helper_acceptance_local.rb to comply with the current litmus
documentation.
> Fix litmus failures

- manifests/repos.pp
- spec/classes/repos_spec.rb
description is translated to name of the repository and yum produces
warnings when it is not defined
> add description to InfluxDB yumrepo

- CHANGELOG.md
- README.md
- manifests/profile/dbcompiler/install.pp
Adding role to mitigate CVE-2020-7943 for Compilers running PuppetDB.
> PuppetDB on Compilers

- files/Process_System_Stats.json
The metrics collector module creates measurements for system processes
named system_processes.CPU, but prior to this commit the example
dashboards used processes.CPU.  This commit fixes the discrepancy.
> Fix measurement names for Process dashboards

- files/Process_System_Stats.json
Prior to this commit, this dashboard used a hardcoded datasource
'influxdb_puppet_metrics'.  This commit makes it configurable via a
dropdown.
> Make datasource for system metrics configurable

- files/Telegraf_Puppetserver_Workload.json
- manifests/dashboards/telegraf.pp
- spec/classes/dashboards/telegraf_spec.rb
Adds a new dashboard for per-borrow metrics and addresses #78
> Add dashboard for JRuby per-borrow metrics

- .fixtures.yml
- metadata.json
Prior to this commit, the modules in the fixtures.yml were on the master
branch. As this can introduce issues during spec testing, this commit
pins the puppet modules to the latest versions.
This alleviates #115 in the short term.
> (GH-115) Pin spec testing modules to a version

- manifests/profile/dbcompiler/install.pp
Honor the value passed in for 'compiler' if specified. This
profile is intended to be used on compilers which are running
PuppetDB along with Puppetserver so using the same value
should work and, in the default case, the behavior is unchanged.
> Use supplied compiler name in dbcompiler

- manifests/dashboards/telegraf.pp
- spec/classes/dashboards/telegraf_spec.rb
The v2 PuppetDB dashboards should be used when PuppetDB is
run on a version of Puppet corresponding to a version of
PuppetDB with no remote access support.
> Fix logic to select the v2 PuppetDB dashboards

- manifests/profile/dbcompiler/install.pp
Expose option to control tidying of telegraf configs on dbcompiler
profile. Default to the setting in puppet_metrics_dashboard.
> Add tidy_telegraf_configs option on dbcompiler profile

- files/Telegraf_File_Sync.json
- files/Telegraf_PuppetDB_Performance_v2.json
- files/Telegraf_Puppetserver_Performance.json
Some of the dashboards didn't seem fully configured for out-of-the-box multi-server support and selection.
This change ensures that the server tag is resolvable and displayed on all graph labels and that servers in a multi-server environment can be filtered by tag.
> Improve multiserver telegraf dashboard support

- files/Telegraf_Postgres.json
- manifests/profile/master/postgres.pp
In a PE DR setup there are two active Postgres instances. Currently multiple Postgres instances are not handled well in terms of data collection nor graphing. This change ensures that the data is properly tagged with the Postgres server name as well as updating the graphs for multi-server support based on the server tag.
> Support multiple Postgres instances

- manifests/profile/master/postgres_access.pp
PE 2019.8.3 introduces the `puppet_enterprise::pg::cert_allowlist_entry` class and deprecates the `puppet_enterprise::pg::cert_whitelist_entry` class. This PR updates the code in this module to correctly handle that change.
> Detect new cert_allowlist_entry class

- .fixtures.yml
- provision.yaml
- rakelib/viewer.rake
This PR ports the functionality of https://github.com/puppetlabs/puppet-metrics-viewer into this repository in an effort to archive https://github.com/puppetlabs/puppet-metrics-viewer. The viewer functionality is provided by new rake tasks which use Litmus and bolt to spin up a local docker container with the dashboard. The metrics from a local directory are then imported into the docker dashboard instance.
This PR adds a new module to the fixtures to be able to import the data into the local dashboard container. 
There are some additional benefits from this functionality
* View a temporary copy of the 'puppet_metrics' dashboards
* Develop dashboards on an ephemeral instance
* Import offline data into the ephemeral instance
**Usage**
There 4 new rake tasks to perform tasks
```
rake …
```
> (SUP-2007) Add local import and viewing of metrics

- CONTRIBUTING.md
Prior to this commit, the contrib docs had information about beaker
which was out of date. This commit updates the contrib docs to leverage
litmus and adds information about the local viewer capability.
> (SUP-2143) Update the contrib docs for litmus

- files/Telegraf_Puppetserver_Workload.json
- manifests/dashboards/telegraf.pp
- spec/classes/dashboards/telegraf_spec.rb
This dashboard was removed accidentally in [this commit](https://github.com/suckatrash/puppet_metrics_dashboard/commit/1f170a6f0859b915ff43e0a152af6f0c0ea976da#diff-b341ecff863d7f692c266178359ad8cd87e5d2ae79288f19e7ea014409ad41bf)
Example:
> re-Add dashboard for JRuby per-borrow metrics

- files/Archive_Postgres.json
- manifests/dashboards/puppet_metrics.pp
- spec/classes/dashboards/puppet_metrics_spec.rb
This commit adds an "Archive Postgres Performance" dashboard that
displays archival data gathered by the `psql_metrics` script
added to version 6.2.0 of the `puppet_metrics_collector` module.
Ref. puppetlabs/puppetlabs-puppet_metrics_collector#71
> (SUP-2195) Add Archive Postgres Performance dashboard

- manifests/dashboards/puppet_metrics.pp
- spec/classes/dashboards/puppet_metrics_spec.rb
Using a slash in a title of a `grafana_dashboard` resource
leads to errors when Puppet tries to manage the dashboard.
> Remove slash from dashboard name

- .fixtures.yml
- metadata.json
Prior to this PR, there were several major versions of dependency
modules that were released, but not compatible with this module. This
commit increases the maximum version of the dependencies for this
module.
This does not increase puppet-telegraf due to incompatibilities in 4.0.0. There is a commit that will fix this in the next release.
> (maint) Increase dependency versions

- manifests/profile/master/install.pp
- spec/classes/profile/master/install_spec.rb
Changes to puppet_metrics_collector::profile::master::install to manage the toml gem required for LDAP authentication. This change will address issue #151.
> (#151) Install toml gem by default.

- README.md
- manifests/init.pp
- manifests/profile/compiler.pp
- manifests/profile/master/install.pp
Updated the Harmful Terminology in the Read and Manifests file per:
blacklist > blocklist
compile master > compiler
high availability > disaster recovery
master of masters > primary server
master > primary server
master (branch) > main (branch)
monolithic > standard 
whitelist > allowlist
> (SUP-2500) Remove Harmful terminology in Readme and Manifests

- .github/workflows/nightly.yml
- .github/workflows/pr_test.yml
- provision.yaml
- spec/spec_helper_acceptance_local.rb
Prior to this commit, the local viewer was failing during the start of
influxdb. This commit adds a cgroup mapping into the container so that
systemd can read the cgroups.
Fixes #172
> (GH-172) Add cgroup mapping for viewer

- README.md
- metadata.json
Prior to this PR, this module supported < 4.0.0 of the
puppet-telegraf module. This PR allows 4.x support now that 4.1.0 is
compatible with this module.
Resolves #158
> (GH-158) Add support for puppet-telegraf 4.1+

- manifests/profile/master/postgres.pp
Before this commit, the connection request from telegraf to PostgreSQL is not able to be authenticated due to SSL connection issue.
With this commit, now the authentication is successful and the Telegraf Postgre Metrics can get data to display.
> (SUP-2779) Fix the bug - telegraf postgres metrics unable to obtain data

- CONTRIBUTING.md
- README.md
Prior to this commit, the manual testing procedure was in the
contributing document. This was an odd place to have that documentation
and was difficult to find. Having it in the contributing guide prevented
us from standardizing the contributing documentation. This commit moves
that section to the main readme.
Resolves #138
> (maint) Move the manual testing docs to the readme

- manifests/profile/compiler.pp
- manifests/profile/puppetdb.pp
The puppetlabs/trapperkeeper-status library that provides the
`/status/v1` API of various PE services will respond with a
HTTP 503 status code if any sub-service is not in a healthy state.
By default, Telegraf HTTP inputs will only accept 200 as a
successful response code. This state of affairs leads to situations
like an outage in `pe-orchestration-services` resulting in Telegraf
rejecting perfectly good JRuby metrics from `pe-puppetserver` on
compilers because the `pcp-broker` sub-service is unhealthy.
This commit updates the Telegraf configuration to accept HTTP 503
as a successful return code in addition to 200 so that an attempt
is made to process and store metrics data during outages of external
services.
> Accept 503 responses from PE /status APIs

- manifests/profile/dbcompiler/install.pp
- spec/classes/profile/dbcompiler/install_spec.rb
This commit updates `puppet_metrics_dashboard::profile::dbcompiler::install`
to pass `enable_client_cert => true` when configuring PuppetDB metrics.
This parameter controls whether `http://` or `https://` is used as the
collection scheme.
As the default port number queried is 8081, which is the SSL port, `https://`
must be used. Additionally, client certificates must be use to authorize
access to the `/status` and `/metrics` API endpoints due to CVE-2020-7943.
> Enable PuppetDB SSL in dbcompiler profile

- manifests/certs.pp
This commit updates the `puppet_metrics_dashboard::certs` defined type
by promoting the `ssl_dir` variable to be a parameter. The default
value remains `$settings::ssldir`, but can be overridden by Hiera.
This change provides users the option to work around two situations
where `$settings::ssldir` does not point to the right location:
- `$settings::ssldir` returns the SSL directory of the _Puppet Server_
or other process compiling the catalog. This is usually-but-not-always
the same directory that the Puppet Agent applying the catalog stores
its keypair in.
- Bolt's `bolt apply` command runs a `puppet apply` process on remote
targets with many major Puppet settings, such as `ssldir`, shifted
into a tempdir sandbox to avoid the possibility of side-effects
that could affect Puppet daemons. …
> Allow ssl_dir to be configured via Hiera

- .fixtures.yml
Per recent changes to [GH security](https://github.blog/2021-09-01-improving-git-protocol-security-github/), updated repo source protocols in `.fixures.yaml`.
* Updated `.fixtures.yaml` to move public repo sources from `git` to `https` protocol.
> (SUP-2923) Replace unencrypted git protocol in .fixtures.yml

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .gitignore
- .pdkignore
- .sync.yml
- Gemfile
- Rakefile
- manifests/profile/puppetdb.pp
- metadata.json
Prior to the commit the auto deploy work flow no longer worked due to  gem incompatibility with changelog generator.
This commit pins octokit to v 4.21.0 to work around this.
The base PDK template was also updates and some minor liniting issues resolved
> Fix auto deploy workflow and update pdk

- CODEOWNERS
Prior to this change, the second rule just overrode the first
> Update to CODEOWNERS to prevent the second entry overwriting the first
